/**
 * @author            : Sree Vamsi Nekkanti
 * @created date      : 28-04-2021
 * @description       : Comment post Scheduler licence delete
 * @testClasses       : TestServiceAppointmentSelector
 * @last modified by  : Daniel Perrella
 * @last modified on  : 06-03-2023
**/


public with sharing class ServiceAppointmentSelector {
    // public static  List<ServiceAppointment> getServiceAppointmentsByIds(List<String> serviceAppointmentIds) {
    //     List<ServiceAppointment> serviceAppointments = [SELECT id, Call_sms__c FROM ServiceAppointment WHERE id IN: serviceAppointmentIds];

    //     return serviceAppointments;
    // }
}